# action.yml
name: 'MCIX datastage compile action'
author: 'Data Migrators Pty Ltd'
description: 'Runs mcix datastage compile'
branding:
  icon: 'zap'
  color: 'blue'

inputs:

  api-key:
    description: 'API key for authentication'
    required: true

  url:
    description: 'URL of the DataStage server'
    required: true

  user:
    description: 'Username for authentication'
    required: true

  report:
    description: 'Path to output the compile report'
    required: false
    default: "compile-report.xml"

  project:
    description: 'DataStage project name'
    required: false     # Required when -project-id not specified
    default: ""

  project-id:
    description: 'DataStage project id'
    required: false     # Required when -project not specified
    default: ""

  include-asset-in-test-name:
    description: 'Whether to include asset names in test names in the report'
    required: false
    default: "false"

outputs:
  return-code:
    description: "The return code of the command"
  report:
    description: "Path to the report XML generated by MCIX DataStage Compile"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PARAM_API_KEY: ${{ inputs.api-key }}
    PARAM_URL: ${{ inputs.url }}
    PARAM_USER: ${{ inputs.user }}
    PARAM_REPORT: ${{ inputs.report }}
    PARAM_PROJECT: ${{ inputs.project }}
    PARAM_PROJECT_ID: ${{ inputs.project-id }}
    PARAM_INCLUDE_ASSET_IN_TEST_NAME: ${{ inputs.include-asset-in-test-name }}
