# action.yml
name: 'mcix unit-test execute action'
author: 'Data Migrators Pty Ltd'
description: 'Runs mcix unit-test execute'
branding:
  icon: 'zap'
  color: 'blue'

inputs:

  api-key:
    description: 'API key for authentication'
    required: true

  url:
    description: 'URL of the DataStage server'
    required: true

  user:
    description: 'Username for authentication'
    required: true

  project:
    description: 'DataStage project name'
    required: false     # Required when -project-id not specified
    default: ""

  project-id:
    description: 'DataStage project id'
    required: false     # Required when -project not specified
    default: ""

  report:
    description: 'Path to output the compile report'
    required: true
    default: "./test-report.xml"

  ignore-test-failures:
    description: 'Ignore test failures (always return 0)'
    required: false

  max-concurrency:
    description: 'Maximum number of concurrently executing test case jobs to run'
    required: false
    default: '8'

  test-suite:
    description: 'The test suite name for this invocation of unit testing'
    required: false
    default: 'mcix tests'

outputs:
  return-code:
    description: "Exit code from mcix unit-test execute"
  report:
    description: "Path to the JUnit XML report generated by mcix unit-test execute"


runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PARAM_API_KEY: ${{ inputs.api-key }}
    PARAM_URL: ${{ inputs.url }}
    PARAM_USER: ${{ inputs.user }}
    PARAM_PROJECT: ${{ inputs.project }}
    PARAM_PROJECT_ID: ${{ inputs.project-id }}
    PARAM_REPORT: ${{ inputs.report }}
    PARAM_IGNORE_TEST_FAILURES: ${{ inputs.ignore-test-failures }}
    PARAM_MAX_CONCURRENCY: ${{ inputs.max-concurrency }}
    PARAM_TEST_SUITE: ${{ inputs.test-suite }}
